default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: CRUD_app_development

test:
  <<: *default
  database: CRUD_app_test

production:
  <<: *default
  database: CRUD_app_production
  username: CRUD_app
  password: <%= ENV['CRUD_APP_DATABASE_PASSWORD'] %>
